name: Firebase App Distribution

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools
        
      - name: Install Google Cloud SDK
        run: |
          # Update the package list and install dependencies
          sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates gnupg
          # Add the Cloud SDK public key
          curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
          # Add the Cloud SDK distribution URI as a package source
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

          # Import the Google Cloud public key
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo tee /usr/share/keyrings/cloud.google.gpg

          # Update and install the Google Cloud SDK
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk
          
      - name: Authenticate with Google Cloud
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          # Authenticate using a service account key
          gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          
      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/account.json
      - name: Fetch version from Firebase Cloud Storage
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          gcloud auth activate-service-account --key-file=/tmp/account.json
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          # Step 2: Read the version number from the file
          CURRENT_VERSION=$(curl -s -H "Authorization: Bearer $ACCESS_TOKEN" \
          "https://firebaseappdistribution.googleapis.com/v1/projects/${{ secrets.PROJECT_NUMBER }}/apps/${{ secrets.FIREBASE_APP_ID }}/releases" | jq -r '.releases[0].displayVersion')
          echo "Current Version: $CURRENT_VERSION"


          # Step 3: Split version number into major, minor, patch
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Step 4: Increment version (patch version in this case)
          PATCH=$((PATCH + 1))
          NEW_VERSION_NUMBER="${MAJOR}.${MINOR}.${PATCH}"
          echo "New Version: $NEW_VERSION_NUMBER"
          # Export the new version to be used in subsequent steps
          echo "NEW_VERSION_NUMBER=$NEW_VERSION_NUMBER" >> $GITHUB_ENV

      - name: Dummy Build
        run: echo "Building"
        # run: exit 1
      - name: Fetch all commits
        run: git fetch --unshallow

      - name: Generate Release Notes
        run: |
          # Set environment vars
          SHA_PULLS_API_URL="https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls"
          currentShaResponse=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$SHA_PULLS_API_URL")
          CURRENT_RUN_DATE=$(echo "$currentShaResponse" | jq -r 'map(select(.merged_at != null)) | .[0].merged_at')
          # PREV_RUN_SHA=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.event.workflow }}/runs?status=completed&branch=main" | jq -r '.workflow_runs[1].head_sha')
          # PREV_RUN_SHA=$(curl -s -H "Authorization: ***" "https://api.github.com/repos/testingstuff190/apk-test/actions/workflows/firebaseDistribute.yml/runs?status=completed&branch=main" | jq -r '.workflow_runs[1].head_sha')
          API_URL="https://api.github.com/repos/testingstuff190/apk-test/actions/workflows/firebaseDistribute.yml/runs?status=completed&branch=main"
          PREV_RUN_SHA=$(curl -s -H "Authorization: ***" "$API_URL" | jq -r '.workflow_runs[] | select(.conclusion == "success") | .head_sha' | head -n 1)
          PREV_RUN_DATE=$(git show -s --format=%ci $PREV_RUN_SHA)
          if [ -z "$PREV_RUN_SHA" ]; then
            echo "No previous successful run found. Skipping release notes generation."
            exit 0
          fi
          # Generate release notes from commits
          RELEASE_NOTES_FILE=releasenotes.txt
          echo "Generated by GitHub Action run: ${{ github.run_id }}" > $RELEASE_NOTES_FILE
          git log --pretty=format:"- %s" $PREV_RUN_SHA..${{ github.sha }} >> $RELEASE_NOTES_FILE
          echo "Release notes generated: $(cat $RELEASE_NOTES_FILE)"

      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/account.json
        run: |
          firebase appdistribution:distribute bitbar-sample-app.apk \
            --app ${{ secrets.FIREBASE_APP_ID }} \
            --groups "testers" \
            --release-notes-file releasenotes.txt \
            --debug
